### ISSUE TITLE
0点不会清除昨天的运势信息

### ISSUE THREAD

**Issue by ChuYanSir** [Twiyin0/koishi-plugin-jryspro#1]
今日运势每天0点不会重置昨天的运势，貌似是必须等待24小时后才会清除。

**Comment by Twiyin0** [comment]
源码选择的时间戳是0点，没有更新可能是巧合
![image](https://github.com/Twiyin0/koishi-plugin-jryspro/assets/87588281/ef59de0b-c69c-42a2-bd61-e0cfc5326225)
或者说你bot所在机器的时区不对，校准一下时间哦

**Comment by Twiyin0** [comment]
如果没有别的问题就先关闭这个issues了，后面有问题再开新的issues
