### ISSUE TITLE
[BUG]使用竖屏图源时图片渲染错位

### ISSUE THREAD

**Issue by xmbhjQAQ** [Twiyin0/koishi-plugin-jryspro#4]
![e18ab00bcc60c1ef58a8c1940f8137d1](https://github.com/Twiyin0/koishi-plugin-jryspro/assets/72352414/15081fc4-2d37-4729-b893-c2bc0b87d476)
好奇怪，之前是好的..
模式选择的是图片渲染

**Comment by Twiyin0** [comment]
从没遇到过的情况，有没有更具体一点的信息

**Comment by xmbhjQAQ** [comment]
在日志里没有看到报错信息，疑似puppeteer渲染出问题了

**Comment by Twiyin0** [comment]
尝试重启puppeteer

**Comment by Twiyin0** [comment]
如果没有别的问题就先关掉这个issues了，后面有问题再开新的issues

**Comment by xmbhjQAQ** [comment]
好了一段时间又这样了，同样没有出现报错信息
