### ISSUE TITLE
希望可以自动调整字体和图片的相对大小

### ISSUE THREAD

**Issue by initialencounter** [Twiyin0/koishi-plugin-jryspro#5]
在渲染图片时，如果图片尺寸较大会显得字体显得很小，不点开图片就看不清文字

希望可以根据图片的比例来调整字体的大小，这样显示起来就能看清字了

**Comment by Twiyin0** [comment]
我有想过这么做，但是做出来的效果很差，目前图片是按照长度来确定的。以前是根据宽度定大小的，但是图片显示不全，所以我后面有时间再重做吧。现在没有时间修复

**Comment by Twiyin0** [comment]
版本已升级，可升级至最新版本
