### ISSUE TITLE
使用QQ适配器时出现报错

### ISSUE THREAD

**Issue by olisc3567** [Twiyin0/koishi-plugin-jryspro#6]
使用QQ适配器时出现的报错，命令执行第一次正常，后续都是这个报错，实测kook适配器没有问题。
![{023B4A08-9230-4613-9B44-04950A1725DA}](https://github.com/Twiyin0/koishi-plugin-jryspro/assets/98386249/547cd7c9-c725-4db3-8768-7a3a41714dc5)
![QQ截图20231224060255](https://github.com/Twiyin0/koishi-plugin-jryspro/assets/98386249/38039e32-2f37-49e3-8f94-9bf0ac695d72)

**Comment by Twiyin0** [comment]
那就是适配器的问题，我这边无法解决，可以向适配器作者提issues

**Comment by Twiyin0** [comment]
问题已修复，请将版本更新至1.3.10
