### ISSUE TITLE
更新新版本后，每日运势不发生变化了。

### ISSUE THREAD

**Issue by Neptune1990** [Twiyin0/koishi-plugin-jryspro#7]
更新新版本后，每日运势不发生变化了。
数据库是MySQL
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.2
    Console: 5.26.6
    Koishi Desktop: 1.0.0

**Comment by Twiyin0** [comment]
我这边也有类似情况，正在尝试修复中……

**Comment by Twiyin0** [comment]
已修复，请将插件升级至 v1.3.12

**Comment by Neptune1990** [comment]
已升级至 v1.3.12，任然每日的运势不发生变化。
