### ISSUE TITLE
如何获取群友的uid

### ISSUE THREAD

**Issue by deadduckQAQ** [Twiyin0/koishi-plugin-jryspro#9]
怎么获取群友的uid啊，一直找不到怎么弄

**Comment by deadduckQAQ** [comment]
[logs.zip](https://github.com/Twiyin0/koishi-plugin-jryspro/files/15181154/logs.zip)

**Comment by deadduckQAQ** [comment]
![665ae0b9302a289cc475ba6bf6ce5c9c](https://github.com/Twiyin0/koishi-plugin-jryspro/assets/168680930/96e997a9-4936-49a8-ae6c-b4d3daec090e)

**Comment by deadduckQAQ** [comment]
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz

Binaries:
    Node: 20.12.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.5
    Console: 5.28.4
    Koishi Desktop: 1.1.1

**Comment by deadduckQAQ** [comment]
[Uploading logs.zip…]()

**Comment by Twiyin0** [comment]
你数据库炸了，换个数据库或者把数据库重启一下
